### ISSUE TITLE
Update to Tailwind v3

### ISSUE THREAD

**Issue by Kuldas** [clupprich/starter-snowpack-tailwind#1]
Hello, 
I would like to ask if there are plans to update to the latest version of Tailwind.

**Comment by Kuldas** [comment]
Thanks you @onurozer - https://github.com/clupprich/starter-snowpack-tailwind/pull/2#issue-1111689574  for update Tailwind and congrats to you first PR! 👏

@clupprich Can I somehow link that request from onurozer to resolve this post?

**P.S.:** When I was reading Tailwind's documentation I noticed that they recommend using the CSSnano tool with PostCSS. 
Have you tried using this for more CSS minification? 

- [Snowpak Doc - PostCSS](https://www.snowpack.dev/guides/postcss/#nav-primary)
- [TailwindCSS - CSSnano](https://tailwindcss.com/docs/optimizing-for-production)

**Comment by clupprich** [comment]
Ah, sorry @Kuldas - I missed this issue.

Well, you basically just did by linking to the PR :)

I'm no longer using Ghost (moved back to Jekyll), so unfortunately haven't tried anything new here.
